# Generated by Django 5.2.9 on 2025-12-15 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('genre', '0001_initial'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='song_covers/')),
                ('audio', models.FileField(upload_to='songs/')),
                ('is_trending', models.BooleanField(default=False)),
                ('is_new_release', models.BooleanField(default=False)),
                ('is_top_chart', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artist.artist')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='genre.genre')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='playlist.playlist')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
