# Generated by Django 5.2.9 on 2025-12-16 07:16

import song.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='songs/', validators=[song.models.validate_audio_file]),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
