# Generated by Django 5.2.9 on 2025-12-15 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('song', '0001_initial'),
        ('user', '0002_user_bio_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', through='user.FavoriteArtist', to='artist.artist'),
        ),
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', through='user.LikedSong', to='song.song'),
        ),
        migrations.CreateModel(
            name='RecentlyPlayedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
                'unique_together': {('user', 'song')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='recently_played_songs',
            field=models.ManyToManyField(blank=True, related_name='recently_played_by_users', through='user.RecentlyPlayedSong', to='song.song'),
        ),
    ]
