# Generated by Django 5.2.9 on 2025-12-17 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('song', '0002_alter_song_audio_alter_song_duration'),
        ('user', '0003_favoriteartist_user_favorite_artists_likedsong_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentlyplayedsong',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recentlyplayedsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='song.song'),
        ),
        migrations.AlterField(
            model_name='recentlyplayedsong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favoriteartist',
            index=models.Index(fields=['user', 'artist'], name='user_favori_user_id_05748a_idx'),
        ),
        migrations.AddIndex(
            model_name='likedsong',
            index=models.Index(fields=['user', 'song'], name='user_likeds_user_id_f08b71_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyplayedsong',
            index=models.Index(fields=['user', '-played_at'], name='user_recent_user_id_922ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyplayedsong',
            index=models.Index(fields=['song'], name='user_recent_song_id_e47b38_idx'),
        ),
    ]
